### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by timmhuang** [Charles-Hong520/AnimeAirDayTracker#1]
I seemed to have encountered an SSL error when running the script:
```
Traceback (most recent call last):
  File "/Users/tim.huang/OpenSource/AnimeAirDayTracker/main.py", line 14, in <module>
    response = requests.get(user_watching_url, headers = {'X-MAL-CLIENT-ID': CLIENT_ID})
  File "/Users/tim.huang/OpenSource/AnimeAirDayTracker/venv/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/tim.huang/OpenSource/AnimeAirDayTracker/venv/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/tim.huang/OpenSource/AnimeAirDayTracker/venv/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/tim.huang/OpenSource/AnimeAirDayTracker/venv/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/tim.huang/OpenSource/AnimeAirDayTracker/venv/lib/python3.10/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.myanimelist.net', port=443): Max retries exceeded with url: /v2/users/basketbals/animelist?status=watching&limit=15&nsfw=true (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)')))
```
@Charles-Hong520 Have you seen this on your local dev environment? Any ideas how to fix this?

**Comment by Charles-Hong520** [comment]
I'm not sure what the issue here is. I uploaded a requirements.txt. It includes the package "certifi". This may solve the problem on your end? If it still doesnt work please let me know.

**Comment by Charles-Hong520** [comment]
I have not seen this in my local environment.
